version: "3.9"
services:
    database:
        image: mysql:5.7.20
        ports:
            - "3309:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: usuarios
            MYSQL_USER: dbadmin
            MYSQL_PASSWORD: dbpassword
        volumes:
            - "./data:/var/lib/mysql"
        networks:
            testing_net:
                ipv4_address: 172.28.1.1
    php:
        build:
            context: ./
            dockerfile: php7.dockerfile
        ports:
            - 80:80
            - "3306:3306"
        links:
            - database
        volumes:
            - "./www:/var/www/html"
#            - "./config/php.ini:/usr/local/etc/php/php.ini"
#            - "./config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
        networks:
            testing_net:
                ipv4_address: 172.28.1.2

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin1
        expose:
            - 3306
        ports:
            - 8000:80
        environment: 
            PMA_HOST: database
        networks:
            testing_net:
                ipv4_address: 172.28.1.3

networks:
    testing_net:
        name: redeConteiner
        ipam:
           driver: default
           config:
              - subnet: 172.28.1.0/16
